version: '3.8'

services:
  slack-alerter:
    build: .
    image: slack-alerter-app
    restart: always
    ports:
      - "8082:8080"
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_CHANNEL_ID=${SLACK_CHANNEL_ID}
      - PORT=8080